### ISSUE TITLE
Tzinfo error?

### ISSUE THREAD

**Issue by dirground** [mattantonelli/ffxiv-hunt-bot#2]
What exactly should I be doing to fix this error?

![image](https://user-images.githubusercontent.com/55258353/64818413-d7773000-d560-11e9-9fd3-a8fbb72c6657.png)

**Comment by mattantonelli** [comment]
The link it refers you to in the error would probably be a good place to start.

**Comment by dirground** [comment]
![image](https://user-images.githubusercontent.com/55258353/64820556-8453ac00-d565-11e9-89e5-de7bbe8c66af.png)
Not really sure what to do here?

**Comment by mattantonelli** [comment]
Again, the error is kind enough to provide you with a suggestion. This problem is specific to your system, so I'm afraid I can't offer much more help than to advise you to read the error carefully and refer to the troubleshooting guide it provides.

**Comment by dirground** [comment]
Is there a way to see it working? I see the bot online and all of that with no errors on cmd but is there anything else I need?

**Comment by mattantonelli** [comment]
You can try adding `send_alive(hunt)` after https://github.com/mattantonelli/ffxiv-hunt-bot/blob/master/lib/hunt_bot/hunts.rb#L30 if you'd like. Definitely don't leave that running for too long, though.
